language: node_js
node_js:
- '8'
before_install:
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: aLaF/PolaUgPHCu646bJZcZzav4LfUS7azLAtshVjX228u9YmzEpi413CK2OC21zaKL3noaPx4jWTtb6BJhdmfVIRUiPTYsGOQBTzw0EDo1mVgFcpWloI5SwHR8hkTk3KnYEkwYIaY8dsSXD8YOdHGiH7HJQ19cdU4dfik+l+wWh/3pZYM0JQ5Q2jSK7yKY9R/YeuSWFP9uYscvsxzB3DlQ7T7Woxofpdm3FQCyGJ6LM8v51p0BDBZZoZmUthhDi8uDqQmCTokgaN+pRpl26Th0RT5gL7aknkIc6GAVIsfW2r2uwgsvqYfg8+waoX5G3uNuxGr5Ws+d/G9NTXLI32kSuuqSo6JjmrMO/wRBULMkfbQuh3zMdPKmC4qFxX3A34egSpZdP3c9VrxWgVxFy/+/xi/jE/l21MqGE1RhvIqCgO1fgXus3DMHnqRnal6+ldn1r6l2BpIOqSJd7pGxpkcmj153LQYF1fu6XPCyMklnNFlD6Kj2zhifRVc0VC+NC11V1J0yVni1uvoRO5UNBjO7zbF+9FCQTsl/k+neGSLw6ncAhZyxTiQPDjkuWESJAi2IrxpMv9XyQkrfdbMwm4E1Vggcc38HodYo18kLxplda2dyNEvhuKovDK7JwWKwIwNDu3PMXcdZYRzSrRyvgYGa22NCy5psnRYnFYLQIho4=
